FEATURE | Choose the html tag <h> to improve SEO
robsontenorio/mary pull request #712
Opened 2024-11-15 13:49 UTC by 9christian9

This feature allows you to decide which <code>h</code> HTML tags to use to improve SEO

2024-11-15 13:53 UTC, 9christian9 commented
#672

2024-11-17 21:06 UTC, 9christian9 commented
@robsontenorio what do you think? Will it be implemented?

2024-11-29 16:35 UTC, igergow requested changes
That's good idea, I was going to suggest something similar, can you make it more precise titleSEO can be something as heading/headingType and the subtitleSEO as subheading/subheadingType?

2024-12-07 21:22 UTC, robsontenorio commented
Thanks for this!

I am delaying it for now because of upcoming maryUI v2 (daisyUI 5 + Tailwind 4).

2024-12-13 16:57 UTC, elliottcoe commented
> Thanks for this!
> 
> I am delaying it for now because of upcoming maryUI v2 (daisyUI 5 + Tailwind 4).

Oh that's great! Wasn't aware of MaryUI V2, exciting 😄

2024-12-13 17:23 UTC, robsontenorio commented
See #623

2025-04-01 01:59 UTC, closed without merging